export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
# NPM global workaround https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
export PATH=~/.npm-global/bin:$PATH
