# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# themes in ~/.oh-my-zsh/themes/
if [ -n "$INSIDE_EMACS" ]; then
    export ZSH_THEME="rawsyntax"
else
    export ZSH_THEME="agnoster"
fi

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Disable autocorrection
DISABLE_CORRECTION="true"

# Change this value to set how frequently ZSH updates¬
export UPDATE_ZSH_DAYS=13
alias ga='git add .'
alias gA='git add -A'
alias gp='git push'
alias gfp='git ftp push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias gctrlz='git reset --hard HEAD@{1}'
alias glast='git show --pretty="format:" --name-only'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gitk='gitk --all'

alias cleanxcode='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
alias killrails='kill -INT $(cat tmp/pids/server.pid)'
alias heute='date +"%Y-%m-%d-%H-%M"'

if [[ "$OSTYPE" == linux* ]]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

if [[ "$OSTYPE" == darwin* ]]; then
    bindkey '^F' forward-word
    bindkey '^B' backward-word
fi

# Use clang with c++ 11 lib as default compiler when trying out c++ files
# from the command line. Xcode already use this library internally
if [[ "$OSTYPE" == darwin* ]]; then
  alias clang='clang++ -std=c++11 -stdlib=libc++'
fi

# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ssh-agent rails git bundler)

#java
#export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")

#bundler editor
export BUNDLER_EDITOR=vim


if [[ "$OSTYPE" == darwin* ]]; then
  #mac os
  export PATH="$HOME/bin:$HOME/.npm-global/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/opt/go/libexec/bin:$HOME/go/bin:/usr/bin:$PATH"
  export ANDROID_HOME=/Library/Android/sdk
else
  #linux
  export PATH="$HOME/bin:$HOME/.npm-global/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/go/bin:$HOME/go/bin:$HOME/local/bin:/usr/bin:$PATH"
fi

export GOPATH=$HOME/go
export VIMRC=$HOME/Dotfiles/vim-files/vim/vimrc
eval "$(rbenv init -)"


#asciidoc package needed for ofSite development
if [[ "$OSTYPE" == darwin* ]]; then
  export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"
fi

#valid only for java 7
export BOOT_JVM_OPTIONS="-XX:MaxPermSize=128m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

# rust autocompletition
export PATH=$PATH:$HOME/.cargo/bin/racer
export RUST_SRC_PATH=$HOME/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

# from https://github.com/robbyrussell/oh-my-zsh/issues/3807
# it probably make sense to move all the export path to the bash_profile. TODO
source ~/.zprofile
source $ZSH/oh-my-zsh.sh

export NVM_DIR="/Users/da1/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
