# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Disable autocorrection
DISABLE_CORRECTION="true"

# Change this value to set how frequently ZSH updates¬
export UPDATE_ZSH_DAYS=13
alias ga='git add .'
alias gA='git add -A'
alias gp='git push'
alias gfp='git ftp push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias killrails='kill -INT $(cat tmp/pids/server.pid)'
alias heute='date +"%Y-%m-%d-%H-%M"'
alias gctrlz='git reset --hard HEAD@{1}'
alias glast='git show --pretty="format:" --name-only'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gitk='gitk --all'

#alias for copy and paste
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ssh-agent rails git bundler)

#java
#export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")

#bundler editor
export BUNDLER_EDITOR=vim

# Customize to your needs...
export PATH="$HOME/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/bin:/usr/local/go/bin:$HOME/go/bin:$HOME/local/bin:$HOME/.cabal/bin:$PATH"
export GOPATH=$HOME/go
export VIMRC=$HOME/Dotfiles/vim-files/vim/vimrc
eval "$(rbenv init -)"

# ruby hakc improvement, tracker
export RUBY_GC_HEAP_INIT_SLOTS=850000
export RUBY_GC_HEAP_FREE_SLOTS=850000
export RUBY_GC_HEAP_GROWTH_FACTOR=1.25
export RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
export RUBY_GC_MALLOC_LIMIT=64000000
export RUBY_GC_OLDMALLOC_LIMIT=64000000

# CHROME_BIN variable needed from npm test command in angulare phonegap
# tutorial
# export CHROME_BIN=/usr/bin/chromium

source $ZSH/oh-my-zsh.sh
