# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# themes in ~/.oh-my-zsh/themes/
ZSH_THEME="agnoster"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Disable autocorrection
DISABLE_CORRECTION="true"

# Change this value to set how frequently ZSH updates¬
export UPDATE_ZSH_DAYS=13
alias ga='git add .'
alias gA='git add -A'
alias gp='git push'
alias gfp='git ftp push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias killrails='kill -INT $(cat tmp/pids/server.pid)'
alias heute='date +"%Y-%m-%d-%H-%M"'
alias gctrlz='git reset --hard HEAD@{1}'
alias glast='git show --pretty="format:" --name-only'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gitk='gitk --all'

if [[ "$OSTYPE" == linux* ]]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

if [[ "$OSTYPE" == darwin* ]]; then
    bindkey '^F' forward-word
    bindkey '^B' backward-word
fi

# Use clang with c++ 11 lib as default compiler when trying out c++ files
# from the command line. Xcode already use this library internally
if [[ "$OSTYPE" == darwin* ]]; then
  alias clang='clang++ -std=c++11 -stdlib=libc++'
fi

# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ssh-agent rails git bundler)

#java
#export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")

#bundler editor
export BUNDLER_EDITOR=vim


if [[ "$OSTYPE" == darwin* ]]; then
  #mac os
  export PATH="$HOME/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/opt/go/libexec/bin:$HOME/go/bin:/usr/bin:$PATH"
  export ANDROID_HOME=/Library/Android/sdk
else
  #linux
  export PATH="$HOME/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/go/bin:$HOME/go/bin:$HOME/local/bin:/usr/bin:$PATH"
fi
# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.3.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:$HOME/bin/stackage/stack:${PATH}"
fi

export GOPATH=$HOME/go
export VIMRC=$HOME/Dotfiles/vim-files/vim/vimrc
eval "$(rbenv init -)"

# CHROME_BIN variable needed from npm test command in angulare phonegap
# tutorial
# export CHROME_BIN=/usr/bin/chromium

source $ZSH/oh-my-zsh.sh
